a=int(input("enter a no1:"))
b=int(input("enter a no2:"))
c=int(input("enter a no3:"))
print("logical operator")
print("(a>b)and(b>c)=",(a>b) and(b>c))
print("(a<b)and (b<c)=",(a<b)and(b<c))
print("(a>=b)or(b>=c)=",(a>=b)or(b>=c))
print("(a<=b)or(b<=c)=",(a<=b)or(b<=c))
print("not(a>b)=",not(a>b))
print("not(b>c)=",not(b>c))