a=int(input("enter a no1:"))
b=int(input("enter a no2:"))
a>b
print("relational operator")
print("(a>b)=",(a>b))
print("(a<b)=",(a<b))
print("(a>=b)=",(a>=b))
print("(a<=b)=",(a<=b))
print("(a==b)=",(a==b))
print("(a!=b)=",(a!=b))